### ISSUE TITLE
可以使用标准的 NFT 作为 VC 的基础 

### ISSUE THREAD

**Issue by leeduckgo** [RandyPen/certificate-SBT#1]

**Comment by RandyPen** [comment]
哈哈，也欢迎推荐一些move上的NFT标准

**Comment by RandyPen** [comment]
刚开通了Discussions

**Comment by RandyPen** [comment]
刚了解到，Sui NFT Standards 还没有出来，将来出来之后，可以作为后续工作

**Comment by RandyPen** [comment]
https://github.com/MystenLabs/sui/blob/main/crates/sui-framework/docs/erc721_metadata.md

**Comment by RandyPen** [comment]
https://forums.sui.io/t/sbt-standards-discussion/22762

**Comment by RandyPen** [comment]
https://forums.sui.io/t/nft-object-display-proposal/4872

**Comment by RandyPen** [comment]
NFT协议相关
https://docs.originbyte.io
https://github.com/capsule-craft/noot-standard
https://github.com/suiet/standard
https://github.com/MystenLabs/sui/pull/4887
https://github.com/MystenLabs/sui/blob/a49613a52d1556386464be7d138c379773f35499/sui_programmability/examples/nft_standard/README.md
https://github.com/MystenLabs/sui/tree/a49613a52d1556386464be7d138c379773f35499/sui_programmability/examples/nft_standard/sources

display(NFT显示层实际上的标准)
https://examples.sui.io/basics/display.html

**Comment by RandyPen** [comment]
达成共识的Sui Display Standard
https://docs.sui.io/build/sui-object-display
